server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: eclientlobby
          uri: lb://eclientlobby
          predicates:
            - Path=/api/server/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
